name: Scale Test Workflow

on:
  push:
    branches:
      - main
env:
  SLEEP_1: 30
  SLEEP_2: 20

jobs:
  parallel_jobs_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2]
    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.SLEEP_1 }}

  lid-ekg-mock:
    runs-on: ubuntu-latest
    needs: [parallel_jobs_1]
    strategy:
      matrix:
        job: [1, 2]

    steps:
      - name: Sleep to mock lid
        uses: jakejarvis/wait-action@master
        with:
          time: ${{ env.SLEEP_1 }}
      - name: Sleep to mock ekg
        uses: jakejarvis/wait-action@master
        with:
          time: ${{ env.SLEEP_2 }}
  parallel_jobs_2:
    runs-on: ubuntu-latest
    needs: [lid-ekg-mock]
    strategy:
      matrix:
        job: [1, 2]

    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.SLEEP_2 }}s
