name: Parallel Sleep and Job Execution

on:
  push:
    branches:
      - main

env:
  SLEEP_1_TIME: 30
  SLEEP_2_TIME: 30
  JOB_1_STEP_1_TIME: 30
  JOB_1_STEP_2_TIME: 30
  JOB_2_STEP_1_TIME: 60
  JOB_2_STEP_2_TIME: 30
  SLEEP_3_TIME: 30
  SLEEP_4_TIME: 30

jobs:
  sleep-1-2:
    runs-on: ubuntu-lateststrategy:
    matrix:
      parallel: 2
    fail-fast: false
    steps:
    - name: Sleep for {{ sleep-3-time }}
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.sleep-3-time }}

    - name: Sleep for {{ sleep-4-time }}
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.sleep-4-time }}
