name: Parallel Sleep and Job Execution

on:
  push:
    branches:
      - main

env:
  SLEEP_1_TIME: 30
  SLEEP_2_TIME: 20
  JOB_1_STEP_1_TIME: 30
  JOB_1_STEP_2_TIME: 20
  JOB_2_STEP_1_TIME: 30
  JOB_2_STEP_2_TIME: 20
  SLEEP_3_TIME: 10
  SLEEP_4_TIME: 10

jobs:
  sleep-1:
    runs-on: ubuntu-latest

    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.SLEEP_1_TIME }}

  sleep-2:
    runs-on: ubuntu-latest

    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.SLEEP_2_TIME }}

  job-1-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2]
        sleep: [30, 20]
    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env['JOB_' + job + '_STEP_' + env.sleep + '_TIME'] }}s

  sleep-3:
    runs-on: ubuntu-latest
    needs: [job-1-2]

    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.SLEEP_3_TIME }}

  sleep-4:
    runs-on: ubuntu-latest
    needs: [job-1-2]
    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.SLEEP_4_TIME }}
