name: Parallel Sleep and Job Execution

on:
  push:
    branches:
      - main

env:
  SLEEP_1_TIME: 30
  SLEEP_2_TIME: 30
  JOB_1_STEP_1_TIME: 30
  JOB_1_STEP_2_TIME: 30
  JOB_2_STEP_1_TIME: 60
  JOB_2_STEP_2_TIME: 30
  SLEEP_3_TIME: 30
  SLEEP_4_TIME: 30

jobs:
  sleep-1-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sleep-1:
          time: ${{ env.SLEEP_1_TIME }}s
        sleep-2:
          time: ${{ env.SLEEP_2_TIME }}s

    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.time }}s

  job-1-2:
    runs-on: ubuntu-latest
    needs: [sleep-1-2]
    strategy:
      matrix:
        job-1:
          step-1: ${{ env.JOB_1_STEP_1_TIME }}s
          step-2: ${{ env.JOB_1_STEP_2_TIME }}s
        job-2:
          step-1: ${{ env.JOB_2_STEP_1_TIME }}s
          step-2: ${{ env.JOB_2_STEP_2_TIME }}s

    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.step-1 }}s

    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.step-2 }}s

  sleep-3-4:
    runs-on: ubuntu-latest
    needs: [job-1-2]
    strategy:
      matrix:
        sleep-3:
          time: ${{ env.SLEEP_3_TIME }}s
        sleep-4:
          time: ${{ env.SLEEP_4_TIME }}s

    steps:
    - name: Sleep for specified time
      uses: jakejarvis/wait-action@master
      with:
        time: ${{ env.time }}s

