name: Parallel Sleep and Job Execution

on:
  push:
    branches:
      - main

jobs:
  job-1-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2]
        include:
          - sleep_1: 30
            sleep_2: 30
    steps:
      - name: Sleep for specified time
        uses: jakejarvis/wait-action@master
        with:
          time: ${{ matrix.sleep_1 }}
      - name: Sleep for specified time
        uses: jakejarvis/wait-action@master
        with:
          time: ${{ matrix.sleep_2 }}

