name: Parallel Sleep and Job Execution

on:
  push:
    branches:
      - main

env:
  SLEEP_1_TIME: 30
  SLEEP_2_TIME: 30
  JOB_1_STEP_1_TIME: 30
  JOB_1_STEP_2_TIME: 30
  JOB_2_STEP_1_TIME: 60
  JOB_2_STEP_2_TIME: 30
  SLEEP_4_TIME: 30

jobs:
  sleep-1:
    runs-on: ubuntu-latest

    steps:
    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ env.SLEEP_1_TIME }}
      run: |
        sleep ${{ env.SLEEP_TIME }}

  sleep-2:
    runs-on: ubuntu-latest

    steps:
    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ env.SLEEP_2_TIME }}
      run: |
        sleep ${{ env.SLEEP_TIME }}

  job-1:
    runs-on: ubuntu-latest
    needs: [sleep-1, sleep-2]

    steps:
    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ env.JOB_1_STEP_1_TIME }}
      run: |
        sleep ${{ env.SLEEP_TIME }}

    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ env.JOB_1_STEP_2_TIME }}
      run: |
        sleep ${{ env.SLEEP_TIME }}

  job-2:
    runs-on: ubuntu-latest
    needs: [sleep-1, sleep-2]

    steps:
    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ env.JOB_2_STEP_1_TIME }}
      run: |
        sleep ${{ env.SLEEP_TIME }}

    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ env.JOB_2_STEP_2_TIME }}
      run: |
        sleep ${{ env.SLEEP_TIME }}

  sleep-3:
    runs-on: ubuntu-latest
    needs: [job-1, job-2]
    name: Sleep for specified time
    inputs:
      sleep-time:
        name: Sleep Time (in seconds)
        description: The number of seconds to sleep
        required: true
        default: "30"

    steps:
    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ inputs.sleep-time }}
      run: |
        sleep ${{ env.SLEEP_TIME }}

  sleep-4:
    runs-on: ubuntu-latest
    needs: [sleep-3]

    steps:
    - name: Sleep for specified time
      env:
        SLEEP_TIME: ${{ env.SLEEP_4_TIME }}
